Traceback (most recent call last):
  File "//anaconda/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "//anaconda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "//anaconda/lib/python3.5/timeit.py", line 337, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.5/timeit.py", line 271, in main
    repeat = int(a)
ValueError: invalid literal for int() with base 10: 'logs/20161121-numerical.log'
